development:
  adapter: postgresql
  database: db/card_it_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/card_it_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/card_it_production
  pool: 5
  timeout: 5000
